"""Backend-neutral interfaces; project models/losses/optimizers are not selected."""

from typing import Protocol


class ModelProtocol(Protocol):
    implementation_id: str
    def predict(self, X, mask): ...
    def state_dict(self) -> dict: ...
    def load_state_dict(self, state: dict): ...


class LossProtocol(Protocol):
    implementation_id: str
    def __call__(self, prediction, target) -> float: ...


class OptimizerProtocol(Protocol):
    implementation_id: str
    def step(self, model, X, mask, target, loss, rng) -> float: ...
    def state_dict(self) -> dict: ...
    def load_state_dict(self, state: dict): ...
